---
- block:
  - name: Get Region ID
    uri:
      url: "https://{{ inventory_hostname }}/api/regions/?filter[]=region=0&expand=resources"
      user: "{{ miq_app_username }}"
      password: "{{ miq_app_password }}"
      method: GET
      validate_certs: no
    register: region_json

  - set_fact:
      query: "resources[?description=='Region 0'].id"

  - name: Extracting Region id from JSON
    set_fact:
      region_id: "{{ region_json.json | json_query(query) | first }}"

  - name: Set max_concurrent_tasks_per_ems value
    uri:
      url: "https://{{ inventory_hostname }}/api/regions/{{ region_id }}/settings/"
      user: "{{ miq_app_username }}"
      password: "{{ miq_app_password }}"
      method: PATCH
      validate_certs: no
      body_format: json
      body:
        action: edit
        transformation:
          limits:
            max_concurrent_tasks_per_ems: "{{ provider_concurrent_max }}"

  tags:
    - miq_set_provider_concurrent_vm_migration_max
