---

- name: Delete CFME logs
  script: roles/v2v.ci/files/del_logs.sh

- name: Start collecting CFME logs
  script: roles/v2v.ci/files/cfme_start_log.sh "v2v_test"

- include_tasks: rhv_start_monitoring.yml
  with_items:
    - "{{ groups['ovirt_conversion_hosts'] }}"
  loop_control:
    loop_var: rhv_item
