---

- name: check if nmon file already exist
  stat:
    path: "{{ nmon_local_dir }}/{{ nmon_tar }}"
  register: nmon_file_exist

- name: Download and extract nmon into local directory "{{ nmon_local_dir }}"
  block:
    - name: Create nmon local directory "{{ nmon_local_dir }}" 
      file: 
        state: directory
        path: "{{ nmon_local_dir }}"

    - name: Download nmon
      get_url: 
        url: "{{ nmon_url }}/{{ nmon_tar }}"
        dest: "{{ nmon_local_dir }}"

    - name: Extract nmon into {{ nmon_local_dir }}
      unarchive:
        src: "{{ nmon_local_dir }}/{{ nmon_tar }}"
        dest: "{{ nmon_local_dir }}"
  when: nmon_file_exist.stat.exists == false

# Install Nmon on CFME, RHV hosts and conversion VMs
- include_tasks: nmon_installation.yml
  with_items:
    - "{{ miq_vm_name }}.{{ miq_vm_dns_domain }}"
    - "{{ groups['ovirt_conversion_hosts'] }}"
    - "{{ groups['ovirt_conversion_host_vms'] }}"
  loop_control:
    loop_var: v2v_item
