---

- name: Add Conversion hosts in order to delegate to them
  add_host:
    name: "{{ item }}"
    ansible_user: root
    ansible_ssh_pass: "{{ hostvars[item].root_password }}"
    ansible_pipelining: true
  with_items:
    - "{{ groups['ovirt_conversion_hosts'] }}"

- debug: var=rhv_storage

- include: '{{role_path}}/tasks/netapp.yml'

- include: '{{role_path}}/tasks/rhv_storage_discovery.yml'

# Add data iSCSI storage domain
- name: Add data iSCSI storage domain
  ovirt_storage_domain:
    auth:
      username: "{{ v2v_ci_rhv_user }}"
      password: "{{ v2v_ci_rhv_password }}"
      hostname: "{{ v2v_ci_rhv_hostname }}"
      insecure: yes
    name: "{{ storage_domain_name }}"
    state: present
    host: "{{ groups['ovirt_conversion_hosts'][0] }}"
    data_center: "{{ data_center_name }}"
    iscsi:
      target: "{{ iscsi_target_wwn }}"
      lun_id:
       - "{{ '3' + create_lun_map_result['lun_naa_id'] }}"
      address: "{{ iscsi_target_ip }}"
    discard_after_delete: True
    wipe_after_delete: True
  when: rhv_storage == 'iscsi'

# Add data FCP storage domain
- name: Add data FCP storage domain
  ovirt_storage_domain:
    auth:
      username: "{{ v2v_ci_rhv_user }}"
      password: "{{ v2v_ci_rhv_password }}"
      hostname: "{{ v2v_ci_rhv_hostname }}"
      insecure: yes
    name: "{{ storage_domain_name }}"
    state: present
    host: "{{ groups['ovirt_conversion_hosts'][0] }}"
    data_center: "{{ data_center_name }}"
    fcp:
      lun_id:
       - "{{ '3' + create_lun_map_result['lun_naa_id'] }}"
    discard_after_delete: True
    wipe_after_delete: True
  when: rhv_storage == 'fcp'
